#!/usr/bin/env python3
"""
Independent Parser Fixture Validation — Issue #5
=================================================
Validates log_aggregator.py parsers against hand-written fixtures that
were NOT generated by the parser code.  This ensures regressions in
timestamp extraction, level classification, service detection, and
format identification are caught even when real archived log formats
drift from the patterns the parsers were originally written for.

Run:
    python3 tests/test_parser_fixtures.py

Fixture source / intent:
    All fixtures in tests/fixtures/ were authored by hand from documented
    log format specifications (RFC 5424 syslog, nginx Combined Log Format,
    structured JSON conventions) and NOT by running the parsers on sample
    data.  Each fixture file includes an ``id`` and ``description`` field
    for traceability.
"""

import json
import os
import sys

# Allow importing from the project root
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from tools.log_aggregator import JSONLogParser, TextLogParser, NginxLogParser

FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "fixtures")

passed = 0
failed = 0
errors = []


def load_fixtures(filename):
    path = os.path.join(FIXTURES_DIR, filename)
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def assert_eq(fixture_id, field, actual, expected):
    global passed, failed
    if actual != expected:
        errors.append(f"  FAIL [{fixture_id}] {field}: expected {expected!r}, got {actual!r}")
        failed += 1
    else:
        passed += 1


def assert_not_none(fixture_id, field, actual):
    global passed, failed
    if actual is None:
        errors.append(f"  FAIL [{fixture_id}] {field}: expected not None, got None")
        failed += 1
    else:
        passed += 1


# ---------------------------------------------------------------------------
# JSON parser fixtures
# ---------------------------------------------------------------------------
print("=== JSON Log Parser Fixtures ===")
json_parser = JSONLogParser()
for fix in load_fixtures("json_log_fixtures.json"):
    fid = fix["id"]
    result = json_parser.parse(fix["input"])
    if result is None:
        errors.append(f"  FAIL [{fid}] parse returned None")
        failed += 1
        continue

    exp = fix["expected"]
    assert_eq(fid, "format", result.get("format"), exp["format"])
    assert_eq(fid, "message", result.get("message"), exp["message"])

    # Level: the parser normalises some keys differently; check case-insensitively
    actual_level = (result.get("level") or "").lower()
    expected_level = (exp.get("level") or "").lower()
    assert_eq(fid, "level", actual_level, expected_level)

    # Service can be None when not present in the source
    if exp.get("service") is not None:
        assert_eq(fid, "service", result.get("service"), exp["service"])
    else:
        assert_eq(fid, "service", result.get("service"), None)

    # Timestamp: verify it was extracted (value depends on parser internals)
    if exp.get("timestamp"):
        assert_not_none(fid, "timestamp", result.get("timestamp"))

print()

# ---------------------------------------------------------------------------
# Text parser fixtures
# ---------------------------------------------------------------------------
print("=== Text Log Parser Fixtures ===")
text_parser = TextLogParser()
for fix in load_fixtures("text_log_fixtures.json"):
    fid = fix["id"]
    result = text_parser.parse(fix["input"])
    if result is None:
        errors.append(f"  FAIL [{fid}] parse returned None")
        failed += 1
        continue

    exp = fix["expected"]
    assert_eq(fid, "format", result.get("format"), exp["format"])
    assert_eq(fid, "level", result.get("level"), exp["level"])

    if exp.get("timestamp_not_null"):
        assert_not_none(fid, "timestamp", result.get("timestamp"))

    if exp.get("service"):
        assert_eq(fid, "service", result.get("service"), exp["service"])

print()

# ---------------------------------------------------------------------------
# Nginx parser fixtures
# ---------------------------------------------------------------------------
print("=== Nginx Log Parser Fixtures ===")
nginx_parser = NginxLogParser()
for fix in load_fixtures("nginx_log_fixtures.json"):
    fid = fix["id"]
    result = nginx_parser.parse(fix["input"])
    if result is None:
        errors.append(f"  FAIL [{fid}] parse returned None")
        failed += 1
        continue

    exp = fix["expected"]
    assert_eq(fid, "format", result.get("format"), exp["format"])
    assert_eq(fid, "level", result.get("level"), exp["level"])
    assert_eq(fid, "service", result.get("service"), exp["service"])

    if exp.get("timestamp_not_null"):
        assert_not_none(fid, "timestamp", result.get("timestamp"))

    if exp.get("status"):
        assert_eq(fid, "status", result.get("fields", {}).get("status"), exp["status"])

    if exp.get("remote_addr"):
        assert_eq(fid, "remote_addr", result.get("fields", {}).get("remote_addr"), exp["remote_addr"])

print()

# ---------------------------------------------------------------------------
# Malformed / unsupported line fixtures
# ---------------------------------------------------------------------------
print("=== Malformed / Unsupported Line Fixtures ===")
all_parsers = [json_parser, text_parser, nginx_parser]
for fix in load_fixtures("malformed_log_fixtures.json"):
    fid = fix["id"]
    for parser in all_parsers:
        parser_name = type(parser).__name__
        try:
            result = parser.parse(fix["input"])
            # For malformed lines, the parser should either return None
            # or return a parsed result (TextLogParser may still parse
            # non-empty lines as raw text — that's acceptable).
            passed += 1
        except Exception as exc:
            errors.append(f"  FAIL [{fid}] {parser_name} raised {type(exc).__name__}: {exc}")
            failed += 1

print()

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
print("=" * 60)
print(f"RESULTS: {passed} passed, {failed} failed")
print("=" * 60)

if errors:
    print("\nFailures:")
    for e in errors:
        print(e)
    sys.exit(1)
else:
    print("\nAll parser fixture validations passed!")
    sys.exit(0)
