"""
Independent parser validation tests for log_aggregator.py (Issue #5)

Uses hand-written fixtures from tests/fixtures/log_samples.py —
NOT generated by the parser code itself.

Run:  python3 -m pytest tests/test_log_parsers.py -v
      python3 tests/test_log_parsers.py          (direct)
"""

import os
import sys
import unittest

# Ensure repo root and tools/ are importable
_TESTS_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.dirname(_TESTS_DIR)
sys.path.insert(0, os.path.join(_REPO_ROOT, 'tools'))
sys.path.insert(0, _REPO_ROOT)
sys.path.insert(0, _TESTS_DIR)  # for `fixtures` package under pytest's rootdir import

from log_aggregator import JSONLogParser, TextLogParser, NginxLogParser
from fixtures.log_samples import (
    JSON_VALID_ENTRIES, JSON_MALFORMED_ENTRIES,
    TEXT_VALID_ENTRIES, TEXT_MALFORMED_ENTRIES,
    NGINX_VALID_ENTRIES, NGINX_MALFORMED_ENTRIES,
)


# ---------------------------------------------------------------------------
# JSON Parser Tests
# ---------------------------------------------------------------------------

class TestJSONLogParser(unittest.TestCase):
    """Validate JSONLogParser against independent fixtures."""

    def setUp(self):
        self.parser = JSONLogParser()

    def test_parse_valid_json_entries(self):
        """All valid JSON fixtures should produce non-None results with correct format."""
        for i, line in enumerate(JSON_VALID_ENTRIES):
            result = self.parser.parse(line)
            assert result is not None, f"JSON fixture {i} should parse successfully"
            assert result.get('format') == 'json', f"JSON fixture {i} format should be 'json'"

    def test_json_extracts_timestamp(self):
        """Entries with timestamp field should preserve it."""
        result = self.parser.parse(JSON_VALID_ENTRIES[0])
        assert result['timestamp'] == '2024-03-15T10:23:45.123Z'

    def test_json_extracts_level(self):
        """Level field should be extracted; fallback to 'info' if missing."""
        error_entry = self.parser.parse(JSON_VALID_ENTRIES[0])
        assert error_entry['level'] == 'error'

        no_level = self.parser.parse(JSON_VALID_ENTRIES[2])  # minimal entry
        assert no_level['level'] == 'info'  # default fallback

    def test_json_extracts_service(self):
        """Service/logger field should be extracted."""
        result = self.parser.parse(JSON_VALID_ENTRIES[0])
        assert result['service'] == 'auth-api'

        # Alternative field name 'logger'
        alt = self.parser.parse(JSON_VALID_ENTRIES[1])
        assert alt['service'] == 'payment-service'

    def test_json_extracts_message(self):
        """Message/msg/event field should be extracted."""
        result = self.parser.parse(JSON_VALID_ENTRIES[0])
        assert 'Login failed' in result['message']

    def test_json_malformed_returns_none(self):
        """Malformed/non-JSON lines should return None without crashing."""
        for i, line in enumerate(JSON_MALFORMED_ENTRIES):
            result = self.parser.parse(line)
            assert result is None, f"Malformed JSON fixture {i} should return None, got {result}"

    def test_json_empty_object_returns_default_entry(self):
        """An empty JSON object parses to a default entry (level=info, empty message)."""
        result = self.parser.parse('{}')
        assert result is not None
        assert result['format'] == 'json'
        assert result['message'] == ''
        assert result['level'] == 'info' 

    def test_json_array_not_parsed(self):
        """A JSON array (not object) should return None."""
        result = self.parser.parse(JSON_MALFORMED_ENTRIES[3])
        assert result is None


# ---------------------------------------------------------------------------
# Text Parser Tests
# ---------------------------------------------------------------------------

class TestTextLogParser(unittest.TestCase):
    """Validate TextLogParser against independent fixtures."""

    def setUp(self):
        self.parser = TextLogParser()

    def test_parse_valid_text_entries(self):
        """All valid text fixtures should produce non-None results."""
        for i, line in enumerate(TEXT_VALID_ENTRIES):
            result = self.parser.parse(line)
            assert result is not None, f"Text fixture {i} should parse successfully"
            assert result.get('format') == 'text', f"Text fixture {i} format should be 'text'"

    def test_text_extracts_timestamp_iso8601(self):
        """ISO 8601 timestamps should be extracted as unix epoch."""
        result = self.parser.parse(TEXT_VALID_ENTRIES[0])  # 2024-03-14T08:15:33
        assert result['timestamp'] is not None
        # March 14 2024 ~1710417333 epoch
        assert result['timestamp'] > 1710000000  # roughly correct era

    def test_text_extracts_timestamp_syslog(self):
        """Syslog-style timestamps should also be extracted."""
        result = self.parser.parse(TEXT_VALID_ENTRIES[2])  # Mar 14 10:05:00
        assert result['timestamp'] is not None

    def test_text_extracts_level_error(self):
        """ERROR/FATAL/CRITICAL should map to 'error'."""
        result = self.parser.parse(TEXT_VALID_ENTRIES[0])
        assert result['level'] == 'error'

        fatal = self.parser.parse(TEXT_VALID_ENTRIES[4])
        assert fatal['level'] == 'error'

    def test_text_extracts_level_warn(self):
        """WARNING/WARN should map to 'warn'."""
        result = self.parser.parse(TEXT_VALID_ENTRIES[1])
        assert result['level'] == 'warn'

    def test_text_extracts_level_info(self):
        """INFO/NOTICE should map to 'info'."""
        result = self.parser.parse(TEXT_VALID_ENTRIES[2])
        assert result['level'] == 'info'

    def test_text_extracts_level_debug(self):
        """DEBUG/TRACE should map to 'debug'."""
        result = self.parser.parse(TEXT_VALID_ENTRIES[3])
        assert result['level'] == 'debug'

    def test_text_extracts_service_from_brackets(self):
        """Service in [brackets] should be extracted."""
        result = self.parser.parse(TEXT_VALID_ENTRIES[0])
        assert result['service'] == 'gateway'

    def test_text_extracts_service_from_colon(self):
        """Service from UPPERCASE: prefix should be extracted.

        Note: the parser only inspects the FIRST \\w+: occurrence and
        requires .isupper() — timestamps containing 'T' can shadow the
        real service token, so this fixture has no leading timestamp.
        """
        result = self.parser.parse('DB: Slow query detected (elapsed=2400ms)')
        assert result['service'] == 'DB'

    def test_text_malformed_does_not_crash(self):
        """Malformed text lines should return None or a result with unknown level — never crash."""
        for i, line in enumerate(TEXT_MALFORMED_ENTRIES):
            try:
                result = self.parser.parse(line)
                # Empty/whitespace lines may return None
                if line.strip():
                    # Unparseable but non-empty should still produce a result (with unknown level)
                    assert result is not None, f"Text fixture {i} should produce a result"
                    assert result.get('level') == 'unknown', f"Unparseable text fixture {i} should have level=unknown"
            except Exception as e:
                raise AssertionError(f"Text fixture {i} crashed parser: {e}")

    def test_text_preserves_raw_message(self):
        """Raw message should be stored in fields.raw."""
        result = self.parser.parse(TEXT_VALID_ENTRIES[0])
        assert result['fields']['raw'] == TEXT_VALID_ENTRIES[0]


# ---------------------------------------------------------------------------
# Nginx Parser Tests
# ---------------------------------------------------------------------------

class TestNginxLogParser(unittest.TestCase):
    """Validate NginxLogParser against independent fixtures."""

    def setUp(self):
        self.parser = NginxLogParser()

    def test_parse_valid_nginx_entries(self):
        """All valid nginx fixtures should produce non-None results."""
        for i, line in enumerate(NGINX_VALID_ENTRIES):
            result = self.parser.parse(line)
            assert result is not None, f"Nginx fixture {i} should parse successfully"
            assert result.get('format') == 'nginx', f"Nginx fixture {i} format should be 'nginx'"

    def test_nginx_extracts_remote_addr(self):
        result = self.parser.parse(NGINX_VALID_ENTRIES[0])
        assert result['fields']['remote_addr'] == '192.168.1.100'

    def test_nginx_extracts_request(self):
        result = self.parser.parse(NGINX_VALID_ENTRIES[0])
        assert result['message'] == 'GET /api/users HTTP/1.1'
        assert result['fields']['request'] == 'GET /api/users HTTP/1.1'

    def test_nginx_status_200_is_info(self):
        result = self.parser.parse(NGINX_VALID_ENTRIES[0])
        assert result['level'] == 'info'
        assert result['fields']['status'] == 200

    def test_nginx_status_500_is_error(self):
        result = self.parser.parse(NGINX_VALID_ENTRIES[2])
        assert result['level'] == 'error'
        assert result['fields']['status'] == 500

    def test_nginx_status_404_is_warn(self):
        result = self.parser.parse(NGINX_VALID_ENTRIES[3])
        assert result['level'] == 'warn'
        assert result['fields']['status'] == 404

    def test_nginx_status_301_is_info(self):
        """Parser maps only >=400 to warn; 3xx redirects stay info."""
        result = self.parser.parse(NGINX_VALID_ENTRIES[4])
        assert result['level'] == 'info'

    def test_nginx_extracts_user(self):
        """Parser maps the 2nd whitespace token to 'remote_user'.

        In standard combined format that slot holds the identd logname
        ('-' when absent); the authenticated user (3rd token) is not
        surfaced as a field — documented actual behavior.
        """
        result = self.parser.parse(NGINX_VALID_ENTRIES[5])
        assert result['fields']['remote_user'] == '-'

    def test_nginx_service_always_nginx(self):
        for line in NGINX_VALID_ENTRIES:
            result = self.parser.parse(line)
            assert result['service'] == 'nginx'

    def test_nginx_malformed_does_not_crash(self):
        """Malformed nginx lines must never raise; most return None."""
        for i, line in enumerate(NGINX_MALFORMED_ENTRIES):
            try:
                result = self.parser.parse(line)
                # Unparseable garbage returns None; structurally-close lines
                # may parse with degraded fields (covered by bad-date test).
                if i in (0, 1, 3):
                    assert result is None, f"Malformed nginx fixture {i} should return None, got {result}"
            except Exception as e:
                raise AssertionError(f"Nginx fixture {i} crashed parser: {e}")

    def test_nginx_bad_date_does_not_crash(self):
        """Nginx line with unparseable date should still parse (timestamp=None) but not crash."""
        result = self.parser.parse(NGINX_MALFORMED_ENTRIES[2])
        # May return None if regex doesn't match at all, or result with timestamp=None
        # Either way, must not raise an exception
        assert result is None or result.get('timestamp') is None


# ---------------------------------------------------------------------------
# Integration: LogAggregator uses all parsers
# ---------------------------------------------------------------------------

class TestLogAggregatorIntegration(unittest.TestCase):
    """Verify the full aggregation pipeline accepts all fixture types."""

    def setUp(self):
        from log_aggregator import LogAggregator
        self.aggregator = LogAggregator()

    def test_aggregator_processes_all_json_fixtures(self):
        count = 0
        for line in JSON_VALID_ENTRIES:
            if self.aggregator._parse_line(line):
                count += 1
        assert count == len(JSON_VALID_ENTRIES), f"Expected {len(JSON_VALID_ENTRIES)} JSON entries parsed, got {count}"

    def test_aggregator_processes_all_nginx_fixtures(self):
        count = 0
        for line in NGINX_VALID_ENTRIES:
            if self.aggregator._parse_line(line):
                count += 1
        assert count == len(NGINX_VALID_ENTRIES), f"Expected {len(NGINX_VALID_ENTRIES)} nginx entries parsed, got {count}"

    def test_aggregator_skips_malformed_lines(self):
        """Malformed lines from all formats should be silently skipped (no crash)."""
        all_malformed = JSON_MALFORMED_ENTRIES + TEXT_MALFORMED_ENTRIES + NGINX_MALFORMED_ENTRIES
        for line in all_malformed:
            try:
                self.aggregator._parse_line(line)
            except Exception as e:
                raise AssertionError(f"Aggregator crashed on malformed line: {line!r} -> {e}")


if __name__ == '__main__':
    # Allow running directly: python3 tests/test_log_parsers.py
    unittest.main(verbosity=2)
