#!/usr/bin/env python3
"""
Independent log-parser validation for Tent of Trials `tools/log_aggregator.py`.

WHY THIS EXISTS
---------------
The legacy log-aggregator test data was generated by the same parser logic, so
tests could false-pass. This script validates the parsers against HAND-WRITTEN
representative log lines that were NOT produced by the parser. It covers the
three supported formats (JSON, plain text, nginx access logs) and asserts the
extracted timestamp, level, service/format, and key fields.

It also proves malformed/unsupported lines do NOT crash parsing (graceful None).

Run:  python3 tools/tests/test_log_parser_fixtures.py
Exit: 0 = all checks passed, 1 = at least one assertion failed.
"""

import os
import sys

# Allow running from repo root or from tools/tests/.
HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(REPO_ROOT, "tools"))

from log_aggregator import (  # noqa: E402
    JSONLogParser,
    TextLogParser,
    NginxLogParser,
)

FIXTURES = os.path.join(HERE, "fixtures")

failures = []


def expect(cond: bool, msg: str) -> None:
    if cond:
        print(f"  [PASS] {msg}")
    else:
        print(f"  [FAIL] {msg}")
        failures.append(msg)


def read_lines(name: str):
    path = os.path.join(FIXTURES, name)
    with open(path, "r", encoding="utf-8") as f:
        return [ln.rstrip("\n") for ln in f if ln.strip()]


def main() -> int:
    json_p = JSONLogParser()
    text_p = TextLogParser()
    nginx_p = NginxLogParser()

    # ------------------------------------------------------------------
    # JSON fixtures
    # ------------------------------------------------------------------
    print("\n== JSON parser (hand-written fixtures) ==")
    json_lines = read_lines("json_sample.log")
    expect(len(json_lines) == 3, "JSON fixture has 3 representative lines")

    e0 = json_p.parse(json_lines[0])
    expect(e0 is not None, "JSON line 1 parses")
    expect(e0["level"] == "error", "JSON line 1 level == 'error'")
    expect(e0["service"] == "payments", "JSON line 1 service == 'payments'")
    expect(e0["timestamp"] == "2024-03-12T08:15:30Z", "JSON line 1 timestamp preserved")
    expect(e0["message"] == "charge failed for txn 9f3a", "JSON line 1 message field extracted")

    e1 = json_p.parse(json_lines[1])
    expect(e1["level"] == "warn", "JSON line 2 maps severity 'warn' -> 'warn'")
    expect(e1["service"] == "cache", "JSON line 2 service == 'cache' (logger field)")

    e2 = json_p.parse(json_lines[2])
    expect(e2["level"] == "info", "JSON line 2 maps 'info' (lvl) -> 'info'")
    expect(e2["service"] == "api", "JSON line 2 service == 'api' (app field)")

    # ------------------------------------------------------------------
    # Plain text fixtures
    # ------------------------------------------------------------------
    print("\n== Text parser (hand-written fixtures) ==")
    text_lines = read_lines("text_sample.log")
    expect(len(text_lines) == 3, "Text fixture has 3 representative lines")

    t0 = text_p.parse(text_lines[0])
    expect(t0 is not None, "Text line 1 parses")
    expect(t0["level"] == "error", "Text line 1 level == 'error' (ERROR token)")
    expect(t0["service"] == "auth", "Text line 1 service == 'auth' ([auth] bracket)")
    expect(isinstance(t0["timestamp"], int) and t0["timestamp"] > 0, "Text line 1 timestamp parsed to unix int")

    t1 = text_p.parse(text_lines[1])
    expect(t1["level"] == "warn", "Text line 2 level == 'warn'")
    expect(t1["timestamp"] is not None, "Text line 2 standard timestamp parsed")

    t2 = text_p.parse(text_lines[2])
    expect(t2["level"] == "debug", "Text line 2 level == 'debug' (DEBUG token)")
    expect(t2["timestamp"] is not None, "Text line 2 syslog-style timestamp parsed")

    # ------------------------------------------------------------------
    # Nginx access-log fixtures
    # ------------------------------------------------------------------
    print("\n== Nginx parser (hand-written fixtures) ==")
    nginx_lines = read_lines("nginx_sample.log")
    expect(len(nginx_lines) == 2, "Nginx fixture has 2 representative lines")

    n0 = nginx_p.parse(nginx_lines[0])
    expect(n0 is not None, "Nginx line 1 parses")
    expect(n0["service"] == "nginx", "Nginx line 1 service == 'nginx'")
    expect(n0["level"] == "info", "Nginx line 1 (status 200) level == 'info'")
    expect(n0["fields"]["status"] == 200, "Nginx line 1 status == 200")
    expect(n0["fields"]["request"] == "GET /api/health HTTP/1.1", "Nginx line 1 request extracted")
    expect(n0["fields"]["remote_addr"] == "127.0.0.1", "Nginx line 1 remote_addr extracted")
    expect(isinstance(n0["timestamp"], int) and n0["timestamp"] > 0, "Nginx line 1 timestamp parsed")

    n1 = nginx_p.parse(nginx_lines[1])
    expect(n1["level"] == "error", "Nginx line 2 (status 500) level == 'error'")
    expect(n1["fields"]["status"] == 500, "Nginx line 2 status == 500")

    # ------------------------------------------------------------------
    # Malformed / unsupported lines must NOT crash
    # ------------------------------------------------------------------
    print("\n== Malformed / unsupported lines (must not crash) ==")
    malformed = read_lines("malformed.log")
    expect(len(malformed) == 4, "Malformed fixture has 4 lines")
    for i, line in enumerate(malformed):
        result = None
        try:
            # Exercise each parser; none should raise.
            json_p.parse(line)
            text_p.parse(line)
            nginx_p.parse(line)
            result = "ok"
        except Exception as exc:  # noqa: BLE001
            result = f"raised: {exc}"
        expect(result == "ok", f"Malformed line {i + 1} handled without exception (got: {result})")

    # A broken JSON line must yield None from the JSON parser, not raise.
    broken_json = json_p.parse('{"this is": "not valid json')
    expect(broken_json is None, "Broken JSON line returns None (no exception)")

    # ------------------------------------------------------------------
    print("\n" + "=" * 60)
    if failures:
        print(f"RESULT: {len(failures)} CHECK(S) FAILED")
        for f in failures:
            print(f"  - {f}")
        return 1
    print("RESULT: ALL INDEPENDENT FIXTURE CHECKS PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
