#!/usr/bin/env python3
"""
Independent parser fixtures for log_aggregator.

These fixtures are based on hand-written representative log lines, not
parser-generated samples. This prevents false passes that occur when
test data is generated by the same parser logic being tested.

Covers: JSON, plain text, and nginx-style log lines.
"""

import json
import os
import sys
import tempfile
from pathlib import Path

# Add parent directory to path so we can import log_aggregator
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "tools"))

from log_aggregator import (
    JSONLogParser,
    TextLogParser,
    NginxLogParser,
    LogAggregator,
)


# ---------------------------------------------------------------------------
# INDEPENDENT FIXTURES
# ---------------------------------------------------------------------------
# These are hand-written log lines, NOT generated by the parser code.
# They represent real-world log formats that the parsers must handle.

JSON_FIXTURES = [
    # Valid JSON log lines
    (
        '{"timestamp": "2026-07-13T10:30:00", "level": "ERROR", "service": "api-gateway", "message": "Connection timeout to upstream service"}',
        {
            "timestamp": "2026-07-13T10:30:00",
            "level": "error",
            "service": "api-gateway",
            "format": "json",
        },
    ),
    (
        '{"time": "2026-07-13T10:31:15", "severity": "WARN", "logger": "db-pool", "msg": "Connection pool at 80% capacity"}',
        {
            "timestamp": "2026-07-13T10:31:15",
            "level": "warn",
            "service": "db-pool",
            "format": "json",
        },
    ),
    (
        '{"@timestamp": "2026-07-13T10:32:00", "lvl": "INFO", "app": "auth-service", "event": "User login successful"}',
        {
            "timestamp": "2026-07-13T10:32:00",
            "level": "info",
            "service": "auth-service",
            "format": "json",
        },
    ),
    # JSON with extra fields preserved
    (
        '{"timestamp": "2026-07-13T10:33:00", "level": "DEBUG", "service": "cache", "message": "Cache miss for key user:12345", "latency_ms": 42, "cache_hit": false}',
        {
            "timestamp": "2026-07-13T10:33:00",
            "level": "debug",
            "service": "cache",
            "format": "json",
        },
    ),
    # Malformed JSON line (should not crash)
    (
        '{"timestamp": "2026-07-13T10:34:00", "level": "INFO", broken json here}',
        None,  # Should return None (not crash)
    ),
    # Empty JSON object
    (
        "{}",
        {
            "timestamp": None,
            "level": "info",
            "service": None,
            "format": "json",
        },
    ),
]

TEXT_FIXTURES = [
    # Standard timestamp log lines
    (
        "2026-07-13 10:30:00 [api-gateway] ERROR: Connection timeout to upstream service",
        {
            "level": "error",
            "service": "api-gateway",
            "format": "text",
        },
    ),
    # ISO8601 timestamp
    (
        "2026-07-13T10:31:15 [db-pool] WARN: Connection pool at 80% capacity",
        {
            "level": "warn",
            "service": "db-pool",
            "format": "text",
        },
    ),
    # INFO level with service in brackets
    (
        "2026-07-13 10:32:00 [auth-service] INFO: User login successful from IP 192.168.1.1",
        {
            "level": "info",
            "service": "auth-service",
            "format": "text",
        },
    ),
    # DEBUG level
    (
        "2026-07-13 10:33:00 [cache] DEBUG: Cache miss for key user:12345",
        {
            "level": "debug",
            "service": "cache",
            "format": "text",
        },
    ),
    # FATAL level
    (
        "2026-07-13 10:35:00 [scheduler] FATAL: Out of memory, terminating process",
        {
            "level": "error",
            "service": "scheduler",
            "format": "text",
        },
    ),
    # CRITICAL level
    (
        "2026-07-13 10:36:00 [payment] CRITICAL: Database connection lost",
        {
            "level": "error",
            "service": "payment",
            "format": "text",
        },
    ),
    # Empty line (should not crash)
    (
        "",
        None,
    ),
    # Whitespace-only line (should not crash)
    (
        "   \t   ",
        None,
    ),
    # Line with no recognizable pattern
    (
        "This is just a random line with no log structure",
        {
            "level": "unknown",
            "service": None,
            "format": "text",
        },
    ),
]

NGINX_FIXTURES = [
    # Standard nginx access log
    (
        '192.168.1.1 - - [13/Jul/2026:10:30:00 +0000] "GET /api/users HTTP/1.1" 200 1234 "-" "Mozilla/5.0"',
        {
            "level": "info",
            "service": "nginx",
            "format": "nginx",
        },
    ),
    # 404 response (should be warn level)
    (
        '10.0.0.1 - frank [13/Jul/2026:10:31:00 +0000] "GET /old-page HTTP/1.1" 404 234 "-" "curl/7.68"',
        {
            "level": "warn",
            "service": "nginx",
            "format": "nginx",
        },
    ),
    # 500 response (should be error level)
    (
        '192.168.1.100 - - [13/Jul/2026:10:32:00 +0000] "POST /api/payment HTTP/1.1" 500 52 "-" "python-requests/2.28"',
        {
            "level": "error",
            "service": "nginx",
            "format": "nginx",
        },
    ),
    # POST request with referer and user agent
    (
        '172.16.0.1 - admin [13/Jul/2026:10:33:00 +0000] "POST /api/data HTTP/2.0" 201 89 "https://example.com/form" "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"',
        {
            "level": "info",
            "service": "nginx",
            "format": "nginx",
        },
    ),
    # Malformed nginx line (should not crash)
    (
        "this is not a valid nginx log line at all",
        None,
    ),
    # Incomplete nginx line
    (
        '192.168.1.1 - - [13/Jul/2026:10:34:00 +0000] "GET /health HTTP/1.1" 200',
        None,
    ),
]

# ---------------------------------------------------------------------------
# PARSER TESTS
# ---------------------------------------------------------------------------


def test_json_parser():
    """Test JSONLogParser against hand-written fixtures."""
    parser = JSONLogParser()
    for line, expected in JSON_FIXTURES:
        result = parser.parse(line)
        if expected is None:
            assert result is None, f"Expected None for line: {line[:60]}, got: {result}"
        else:
            assert result is not None, f"Expected result for line: {line[:60]}"
            for key, val in expected.items():
                if key == "timestamp":
                    continue  # timestamp format varies; skip exact match
                assert result.get(key) == val, (
                    f"Mismatch for key '{key}' on line: {line[:60]}\n"
                    f"  Expected: {val}\n"
                    f"  Got: {result.get(key)}"
                )
    print(f"  ✓ JSONLogParser: {len([e for e in JSON_FIXTURES if e[1] is not None])} valid, "
          f"{len([e for e in JSON_FIXTURES if e[1] is None])} malformed cases passed")


def test_text_parser():
    """Test TextLogParser against hand-written fixtures."""
    parser = TextLogParser()
    for line, expected in TEXT_FIXTURES:
        result = parser.parse(line)
        if expected is None:
            assert result is None, f"Expected None for line: {repr(line[:60])}, got: {result}"
        else:
            assert result is not None, f"Expected result for line: {repr(line[:60])}"
            for key, val in expected.items():
                if key == "timestamp":
                    continue
                assert result.get(key) == val, (
                    f"Mismatch for key '{key}' on line: {repr(line[:60])}\n"
                    f"  Expected: {val}\n"
                    f"  Got: {result.get(key)}"
                )
    print(f"  ✓ TextLogParser: {len([e for e in TEXT_FIXTURES if e[1] is not None])} valid, "
          f"{len([e for e in TEXT_FIXTURES if e[1] is None])} malformed/empty cases passed")


def test_nginx_parser():
    """Test NginxLogParser against hand-written fixtures."""
    parser = NginxLogParser()
    for line, expected in NGINX_FIXTURES:
        result = parser.parse(line)
        if expected is None:
            assert result is None, f"Expected None for line: {line[:80]}, got: {result}"
        else:
            assert result is not None, f"Expected result for line: {line[:80]}"
            for key, val in expected.items():
                if key == "timestamp":
                    continue
                assert result.get(key) == val, (
                    f"Mismatch for key '{key}' on line: {line[:80]}\n"
                    f"  Expected: {val}\n"
                    f"  Got: {result.get(key)}"
                )
    print(f"  ✓ NginxLogParser: {len([e for e in NGINX_FIXTURES if e[1] is not None])} valid, "
          f"{len([e for e in NGINX_FIXTURES if e[1] is None])} malformed cases passed")


def test_aggregator_integration():
    """Test that LogAggregator correctly processes all fixture types."""
    aggregator = LogAggregator()

    # Write fixture lines to a temp file and process it
    all_lines = []
    all_lines.extend(f[0] for f in JSON_FIXTURES if f[1] is not None)
    all_lines.extend(f[0] for f in TEXT_FIXTURES if f[1] is not None)
    all_lines.extend(f[0] for f in NGINX_FIXTURES if f[1] is not None)

    with tempfile.NamedTemporaryFile(mode="w", suffix=".log", delete=False) as f:
        f.write("\n".join(all_lines) + "\n")
        temp_path = f.name

    try:
        count = aggregator.process_file(temp_path)
        summary = aggregator.get_summary()

        # Verify counts
        expected_valid = (
            sum(1 for f in JSON_FIXTURES if f[1] is not None)
            + sum(1 for f in TEXT_FIXTURES if f[1] is not None)
            + sum(1 for f in NGINX_FIXTURES if f[1] is not None)
        )
        assert count == expected_valid, (
            f"Expected {expected_valid} parsed entries, got {count}"
        )
        assert summary["total_entries"] == expected_valid, (
            f"Summary mismatch: expected {expected_valid}, got {summary['total_entries']}"
        )

        # Verify level counts are populated
        assert len(summary["by_level"]) > 0, "by_level should not be empty"
        assert summary["error_rate"] >= 0, "error_rate should be >= 0"

        print(f"  ✓ Aggregator integration: {count} entries processed correctly")
        print(f"    Levels: {summary['by_level']}")
        print(f"    Services: {summary['by_service']}")
        print(f"    Error rate: {summary['error_rate']}%")
    finally:
        os.unlink(temp_path)


def test_malformed_lines_dont_crash():
    """Test that malformed lines don't crash parsing."""
    parser = JSONLogParser()
    malformed_lines = [
        '{"broken": "json"',
        "{not json at all}",
        "just a plain string",
        "",
        "   ",
        "null",
        "12345",
    ]
    for line in malformed_lines:
        try:
            result = parser.parse(line)
            # Should return None, not crash
        except Exception as e:
            assert False, f"JSONLogParser crashed on line {repr(line)}: {e}"

    parser = TextLogParser()
    for line in malformed_lines:
        try:
            result = parser.parse(line)
        except Exception as e:
            assert False, f"TextLogParser crashed on line {repr(line)}: {e}"

    parser = NginxLogParser()
    for line in malformed_lines:
        try:
            result = parser.parse(line)
        except Exception as e:
            assert False, f"NginxLogParser crashed on line {repr(line)}: {e}"

    print(f"  ✓ Malformed lines: all parsers handle {len(malformed_lines)} crash cases gracefully")


def test_service_breakdown():
    """Test service breakdown aggregation."""
    aggregator = LogAggregator()
    lines = [
        '{"timestamp": "2026-07-13T10:00:00", "level": "ERROR", "service": "api", "message": "err1"}',
        '{"timestamp": "2026-07-13T10:01:00", "level": "INFO", "service": "api", "message": "ok"}',
        '{"timestamp": "2026-07-13T10:02:00", "level": "WARN", "service": "db", "message": "slow"}',
        '{"timestamp": "2026-07-13T10:03:00", "level": "ERROR", "service": "db", "message": "conn failed"}',
        '{"timestamp": "2026-07-13T10:04:00", "level": "DEBUG", "service": "cache", "message": "miss"}',
    ]

    with tempfile.NamedTemporaryFile(mode="w", suffix=".log", delete=False) as f:
        f.write("\n".join(lines) + "\n")
        temp_path = f.name

    try:
        aggregator.process_file(temp_path)
        breakdown = aggregator.get_service_breakdown()

        assert "api" in breakdown, "Service 'api' should be in breakdown"
        assert "db" in breakdown, "Service 'db' should be in breakdown"
        assert "cache" in breakdown, "Service 'cache' should be in breakdown"

        assert breakdown["api"]["total"] == 2
        assert breakdown["api"]["errors"] == 1
        assert breakdown["api"]["infos"] == 1

        assert breakdown["db"]["total"] == 2
        assert breakdown["db"]["errors"] == 1
        assert breakdown["db"]["warns"] == 1

        assert breakdown["cache"]["total"] == 1
        assert breakdown["cache"]["debugs"] == 1

        print(f"  ✓ Service breakdown: 3 services, {sum(s['total'] for s in breakdown.values())} entries")
    finally:
        os.unlink(temp_path)


def test_error_timeline():
    """Test error timeline aggregation."""
    aggregator = LogAggregator()
    lines = [
        '{"timestamp": "2026-07-13T10:00:00", "level": "ERROR", "service": "api", "message": "err1"}',
        '{"timestamp": "2026-07-13T11:00:00", "level": "ERROR", "service": "api", "message": "err2"}',
        '{"timestamp": "2026-07-13T11:30:00", "level": "ERROR", "service": "db", "message": "err3"}',
    ]

    with tempfile.NamedTemporaryFile(mode="w", suffix=".log", delete=False) as f:
        f.write("\n".join(lines) + "\n")
        temp_path = f.name

    try:
        aggregator.process_file(temp_path)
        timeline = aggregator.get_error_timeline()

        assert len(timeline) == 2, f"Expected 2 hours with errors, got {len(timeline)}"
        # 10:00 and 11:00
        hours = [t["hour"] for t in timeline]
        assert any("10:00" in h for h in hours), "Expected 10:00 hour in timeline"
        assert any("11:00" in h for h in hours), "Expected 11:00 hour in timeline"

        print(f"  ✓ Error timeline: {len(timeline)} hours with errors")
    finally:
        os.unlink(temp_path)


def test_search():
    """Test log search functionality."""
    aggregator = LogAggregator()
    lines = [
        '{"timestamp": "2026-07-13T10:00:00", "level": "ERROR", "service": "api", "message": "database connection timeout"}',
        '{"timestamp": "2026-07-13T10:01:00", "level": "INFO", "service": "api", "message": "request completed"}',
        '{"timestamp": "2026-07-13T10:02:00", "level": "WARN", "service": "db", "message": "slow query detected"}',
    ]

    with tempfile.NamedTemporaryFile(mode="w", suffix=".log", delete=False) as f:
        f.write("\n".join(lines) + "\n")
        temp_path = f.name

    try:
        aggregator.process_file(temp_path)

        results = aggregator.search("timeout")
        assert len(results) == 1, f"Expected 1 result for 'timeout', got {len(results)}"

        results = aggregator.search("request")
        assert len(results) == 1, f"Expected 1 result for 'request', got {len(results)}"

        results = aggregator.search("nonexistent")
        assert len(results) == 0, f"Expected 0 results for 'nonexistent', got {len(results)}"

        print(f"  ✓ Search: all 3 queries returned correct results")
    finally:
        os.unlink(temp_path)


def test_export_csv():
    """Test CSV export doesn't crash."""
    aggregator = LogAggregator()
    lines = [
        '{"timestamp": "2026-07-13T10:00:00", "level": "INFO", "service": "test", "message": "test export"}',
    ]

    with tempfile.NamedTemporaryFile(mode="w", suffix=".log", delete=False) as f:
        f.write("\n".join(lines) + "\n")
        temp_path = f.name

    try:
        aggregator.process_file(temp_path)
        csv_path = temp_path + ".csv"
        try:
            aggregator.export_csv(csv_path)
            assert os.path.exists(csv_path), "CSV file should exist"
            with open(csv_path) as f:
                content = f.read()
            assert "timestamp" in content, "CSV should have header"
            print(f"  ✓ CSV export: file created successfully")
        finally:
            if os.path.exists(csv_path):
                os.unlink(csv_path)
    finally:
        os.unlink(temp_path)


def test_export_json():
    """Test JSON export doesn't crash."""
    aggregator = LogAggregator()
    lines = [
        '{"timestamp": "2026-07-13T10:00:00", "level": "INFO", "service": "test", "message": "test export"}',
    ]

    with tempfile.NamedTemporaryFile(mode="w", suffix=".log", delete=False) as f:
        f.write("\n".join(lines) + "\n")
        temp_path = f.name

    try:
        aggregator.process_file(temp_path)
        json_path = temp_path + ".json"
        try:
            aggregator.export_json(json_path)
            assert os.path.exists(json_path), "JSON file should exist"
            with open(json_path) as f:
                data = json.load(f)
            assert "summary" in data, "JSON export should have summary"
            assert "entries" in data, "JSON export should have entries"
            print(f"  ✓ JSON export: file created successfully")
        finally:
            if os.path.exists(json_path):
                os.unlink(json_path)
    finally:
        os.unlink(temp_path)


def test_gz_file_processing():
    """Test that gzipped log files are processed correctly."""
    import gzip
    aggregator = LogAggregator()
    line = '{"timestamp": "2026-07-13T10:00:00", "level": "INFO", "service": "test", "message": "gzip test"}'

    with tempfile.NamedTemporaryFile(mode="wb", suffix=".log.gz", delete=False) as f:
        with gzip.open(f, "wt") as gz:
            gz.write(line + "\n")
        temp_path = f.name

    try:
        count = aggregator.process_file(temp_path)
        assert count == 1, f"Expected 1 entry from gzip, got {count}"
        print(f"  ✓ Gzip processing: {count} entry parsed from .gz file")
    finally:
        os.unlink(temp_path)


def test_hourly_counts():
    """Test hourly count aggregation."""
    aggregator = LogAggregator()
    lines = [
        '{"timestamp": "2026-07-13T10:00:00", "level": "INFO", "service": "a", "message": "m1"}',
        '{"timestamp": "2026-07-13T10:30:00", "level": "INFO", "service": "a", "message": "m2"}',
        '{"timestamp": "2026-07-13T11:00:00", "level": "INFO", "service": "a", "message": "m3"}',
        '{"timestamp": "2026-07-13T11:45:00", "level": "INFO", "service": "a", "message": "m4"}',
    ]

    with tempfile.NamedTemporaryFile(mode="w", suffix=".log", delete=False) as f:
        f.write("\n".join(lines) + "\n")
        temp_path = f.name

    try:
        aggregator.process_file(temp_path)
        summary = aggregator.get_summary()
        hourly = summary["by_hour"]
        assert len(hourly) == 2, f"Expected 2 hours, got {len(hourly)}"
        print(f"  ✓ Hourly counts: {len(hourly)} distinct hours tracked")
    finally:
        os.unlink(temp_path)


if __name__ == "__main__":
    print("\n=== Parser Fixture Tests ===\n")

    tests = [
        ("JSON Parser", test_json_parser),
        ("Text Parser", test_text_parser),
        ("Nginx Parser", test_nginx_parser),
        ("Aggregator Integration", test_aggregator_integration),
        ("Malformed Lines", test_malformed_lines_dont_crash),
        ("Service Breakdown", test_service_breakdown),
        ("Error Timeline", test_error_timeline),
        ("Search", test_search),
        ("CSV Export", test_export_csv),
        ("JSON Export", test_export_json),
        ("Gzip Processing", test_gz_file_processing),
        ("Hourly Counts", test_hourly_counts),
    ]

    passed = 0
    failed = 0

    for name, func in tests:
        print(f"  [{name}]")
        try:
            func()
            passed += 1
        except Exception as e:
            print(f"  ✗ FAILED: {e}")
            import traceback
            traceback.print_exc()
            failed += 1
        print()

    print(f"  Results: {passed} passed, {failed} failed, {len(tests)} total")
    sys.exit(0 if failed == 0 else 1)
