"""
Independent log parser fixtures — hand-written representative log lines.

These fixtures are NOT generated by the parser code itself.
They are crafted to resemble real production log output from
common sources (application JSON logs, syslog-style text,
and Nginx access logs). Use these to validate parser behavior
without the false-pass risk of parser-generated test data.

Source/intent:
- JSON: mimics structured logging from a Node.js/Python app (pino/winston style)
- Text: mimics syslog and application console output
- Nginx: mimics standard combined log format from a reverse proxy
- Malformed: edge cases that should not crash parsing
"""

# ---------------------------------------------------------------------------
# JSON log fixtures (structured)
# ---------------------------------------------------------------------------

JSON_VALID_ENTRIES = [
    # Standard structured log with all expected fields
    '{"timestamp":"2024-03-15T10:23:45.123Z","level":"error","service":"auth-api","message":"Login failed for user_id=84729","requestId":"req-abc-123","duration_ms":42}',
    # Alternative field names (time, severity, logger) that parser should handle
    '{"time":"2024-03-15T11:00:00Z","severity":"WARN","logger":"payment-service","msg":"Retry webhook delivery attempt 3/5","retryCount":3,"targetUrl":"https://example.com/hooks/pay"}',
    # Minimal valid JSON log — only message, rest defaults
    '{"message":"Health check passed","status":"ok"}',
    # JSON with nested object in message
    '{"timestamp":"2024-03-15T12:30:00Z","level":"info","service":"scheduler","message":"Job batch_complete triggered","job":{"id":"job-991","type":"email-digest","count":1420}}',
    # Debug-level entry
    '{"timestamp":"2024-03-15T13:15:22Z","level":"debug","service":"db-pool","message":"Connection acquired from pool","poolSize":10,"active":3,"idle":7}',
]

JSON_MALFORMED_ENTRIES = [
    '',                                    # empty string
    'not json at all',                     # plain text, not JSON
    '{broken: json}',                      # unquoted keys
    '["array","not","object"]',           # JSON array, not dict
]


# ---------------------------------------------------------------------------
# Plain text log fixtures
# ---------------------------------------------------------------------------

TEXT_VALID_ENTRIES = [
    # ISO 8601 timestamp + level + service in brackets + message
    '2024-03-14T08:15:33 ERROR [gateway] Upstream timeout after 30s, retrying...',
    # Standard datetime format + WARN level
    '2024-03-14 09:01:02 WARNING | cache-miss on key:user:profile:55291',
    # Syslog-style timestamp + INFO
    'Mar 14 10:05:00 INFO  [background-worker] Processed 152 queue items in 3.2s',
    # DEBUG with service from colon pattern
    '2024-03-14T11:20:44 DEBUG DB: Slow query detected (elapsed=2400ms) SELECT * FROM users WHERE active=1',
    # FATAL / CRITICAL level
    '2024-03-14 12:00:00 FATAL [kernel] Out of memory, killing process',
    # NOTICE level (maps to info)
    'Mar 14 13:00:00 NOTICE cron: Starting daily backup job',
]

TEXT_MALFORMED_ENTRIES = [
    '',                                    # empty line
    '   ',                                 # whitespace only
    '\t\n',                                # control characters only
    'this line has no timestamp or level at all',  # unparseable but should not crash
]


# ---------------------------------------------------------------------------
# Nginx combined log format fixtures
# ---------------------------------------------------------------------------

NGINX_VALID_ENTRIES = [
    # Standard GET 200
    '192.168.1.100 - - [15/Mar/2024:14:23:10 +0000] "GET /api/users HTTP/1.1" 200 1234 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"',
    # POST 201 (created)
    '10.0.0.42 - admin [15/Mar/2024:14:25:33 +0000] "POST /api/orders HTTP/1.1" 201 567 "https://example.com/checkout" "Mozilla/5.0"',
    # 500 error (should map to level=error)
    '172.16.0.1 - - [15/Mar/2024:14:30:00 +0000] "GET /api/health HTTP/1.1" 500 23 "-" "curl/7.68.0"',
    # 404 (should map to level=warn)
    '192.168.1.50 - - [15/Mar/2024:14:35:22 +0000] "GET /old-page HTTP/1.1" 404 128 "-" "Googlebot/2.1"',
    # 301 redirect (warn)
    '10.0.0.1 - - [15/Mar/2024:14:40:00 +0000] "GET /blog/post HTTP/1.1" 301 0 "-" "Mozilla/5.0 (Macintosh)"',
    # With authenticated user
    '192.168.1.200 - john_doe [15/Mar/2024:14:45:55 +0000] "DELETE /api/sessions/current HTTP/1.1" 204 0 "https://app.example.com/settings" "Mozilla/5.0"',
]

NGINX_MALFORMED_ENTRIES = [
    '',                                    # empty
    'this is not an nginx log line at all',
    '192.168.1.1 - - [invalid-date] "GET / HTTP/1.1" 200 0 "-" "-"',  # bad date format (should not crash)
    'GARBAGE DATA $$$ %% @@',               # complete garbage (should not crash)
]
