"""
Independent hand-written log parser fixtures.

These fixtures are written by hand to avoid the circular dependency
where parser tests validate against samples generated by the same
parser code. Each fixture represents a realistic log line from
production-like scenarios across JSON, plain-text, and nginx formats.

A malformed/unsupported line is included to verify the parser
handles bad input gracefully without crashing.
"""

# ---------------------------------------------------------------------------
# JSON format log fixtures
# ---------------------------------------------------------------------------

JSON_LOG_LINES = [
    # Standard JSON with timestamp, level, service, message
    '{"timestamp": "2024-03-15T10:30:00Z", "level": "INFO", "service": "api-gateway", "message": "Request processed successfully"}',
    # JSON with alternative field names (time, severity, logger)
    '{"time": "2024-03-15T10:31:00Z", "severity": "ERROR", "logger": "auth-service", "msg": "Authentication failed for user abc123"}',
    # JSON with @timestamp format and nested fields
    '{"@timestamp": "2024-03-15T10:32:00Z", "level": "WARN", "service": "payment-worker", "message": "Retry attempt 3/5 for transaction tx-98765", "retry_count": 3}',
    # JSON with DEBUG level
    '{"timestamp": "2024-03-15T10:33:00Z", "level": "DEBUG", "service": "db-connector", "message": "Connection pool: 12/20 active connections"}',
    # JSON with CRITICAL level and nested context
    '{"timestamp": "2024-03-15T10:34:00Z", "level": "CRITICAL", "service": "monitoring", "message": "Memory usage above 95% threshold", "memory_usage_pct": 96.2}',
    # JSON with lvl shorthand
    '{"timestamp": "2024-03-15T10:35:00Z", "lvl": "INFO", "app": "cron-scheduler", "message": "Daily cleanup job completed"}',
    # JSON with empty message field
    '{"timestamp": "2024-03-15T10:36:00Z", "level": "INFO", "service": "health-check", "message": ""}',
]

# ---------------------------------------------------------------------------
# Plain text log fixtures
# ---------------------------------------------------------------------------

TEXT_LOG_LINES = [
    # Standard format: timestamp level [service] message
    "2024-03-15 10:30:00 INFO [api-gateway] Request processed successfully",
    # Error with component tag
    "2024-03-15 10:31:00 ERROR [auth-service] Authentication failed for user abc123",
    # Warning level
    "2024-03-15 10:32:00 WARN [payment-worker] Retry attempt 3/5 for transaction tx-98765",
    # Debug level
    "2024-03-15 10:33:00 DEBUG [db-connector] Connection pool: 12/20 active connections",
    # WARNING (full word, not WARN)
    "2024-03-15 10:34:00 WARNING [rate-limiter] Rate limit exceeded for IP 192.168.1.100",
    # FATAL level
    "2024-03-15 10:35:00 FATAL [kernel] Kernel panic: out of memory",
    # Syslog-style (no service brackets, service extracted via prefix pattern)
    "2024-03-15 10:36:00 INFO app-server: Health check passed",
    # ISO8601 timestamp
    "2024-03-15T10:37:00 INFO [scheduler] Job completed successfully",
    # No level keyword (should result in 'unknown')
    "2024-03-15 10:38:00 [system] Periodic maintenance running",
    # Service name without brackets (uppercase prefix)
    "2024-03-15 10:39:00 WARN DB_CONNECTOR: Connection pool nearing capacity",
]

# ---------------------------------------------------------------------------
# Nginx-style log fixtures
# ---------------------------------------------------------------------------

NGINX_LOG_LINES = [
    # Standard GET request, 200 OK
    '192.168.1.1 - - [15/Mar/2024:10:30:00 +0000] "GET /api/health HTTP/1.1" 200 612 "-" "curl/7.68.0"',
    # POST request with referer and user-agent
    '10.0.0.1 - admin [15/Mar/2024:10:31:00 +0000] "POST /api/users HTTP/1.1" 201 128 "https://app.example.com/admin" "Mozilla/5.0 (X11; Linux x86_64)"',
    # 500 Internal Server Error
    '192.168.1.100 - - [15/Mar/2024:10:32:00 +0000] "GET /api/orders HTTP/1.1" 500 89 "-" "PostmanRuntime/7.36.0"',
    # 404 Not Found
    '172.16.0.50 - - [15/Mar/2024:10:33:00 +0000] "GET /old-endpoint HTTP/1.1" 404 27 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"',
    # 403 Forbidden
    '192.168.1.200 - bob [15/Mar/2024:10:34:00 +0000] "DELETE /api/admin/users HTTP/1.1" 403 42 "-" "curl/7.68.0"',
    # Request with query string
    '10.0.0.5 - - [15/Mar/2024:10:35:00 +0000] "GET /api/search?q=test&page=1 HTTP/1.1" 200 2345 "https://www.google.com/" "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0)"',
]

# ---------------------------------------------------------------------------
# Malformed / unsupported log line fixtures
# ---------------------------------------------------------------------------

MALFORMED_LOG_LINES = [
    # Empty string
    "",
    # Completely invalid data
    "This is not a valid log line in any supported format",
    # Binary garbage
    "\x00\x01\x02\x03\x04\xff\xfe\xfd",
    # JSON that's not a dict (JSON parser should return None)
    "[1, 2, 3]",
    # JSON that's a plain string
    '"just a string"',
    # Nearly valid nginx but with broken timestamp
    '192.168.1.1 - - [NOT-A-DATE] "GET / HTTP/1.1" 200 612 "-" "-"',
    # Incomplete nginx line (missing fields)
    '192.168.1.1 - - [15/Mar/2024:10:30:00 +0000] "GET /',
    # Random special characters
    "!!!@@@###$$$%%%^^^&&&***",
]
