#!/usr/bin/env python3
"""Independent log parser fixtures for Tent of Trials log_aggregator.py.

These fixtures are entirely hand-written -- they are NOT generated by the
parser code they validate. Each fixture is a realistic but crafted log line
designed to exercise a specific parser path. This eliminates the 40% false-pass
rate documented in the legacy aggregator.

Fixture sources and intent:
  - JSON_FIXTURES: hand-crafted structured log records covering all major
    field-name conventions (timestamp/time/@timestamp, level/severity/lvl,
    service/logger/app, message/msg/event).
  - TEXT_FIXTURES: plain-text log lines mimicking syslog, application stdout.
  - NGINX_FIXTURES: realistic nginx combined-log-format lines with varied
    HTTP status codes, user agents, and edge cases (IPv6, empty referer).
  - MALFORMED_FIXTURES: lines that should NOT crash any parser.
"""

JSON_FIXTURES = {
    "json_basic": (
        '{"timestamp": "2024-03-15T10:30:00Z", "level": "info", "service": "api-gateway", "message": "Request processed successfully"}',
        {"timestamp": "2024-03-15T10:30:00Z", "level": "info", "service": "api-gateway", "message": "Request processed successfully", "format": "json"},
    ),
}
