#!/usr/bin/env python3
"""
Independent parser fixture tests for log_aggregator.py.

These fixtures are HAND-WRITTEN to represent realistic production log lines
in JSON, plain-text, and nginx formats. They are intentionally NOT generated
by the parser code under test, so they serve as an independent oracle for
verifying that LogParser subclasses correctly extract timestamp, level,
service/format, and key fields.

Run:
    python3 tools/test_log_aggregator.py
or:
    python3 -m pytest tools/test_log_aggregator.py
"""

import json
import os
import sys
import unittest
from datetime import datetime, timezone

# Make the module importable whether run from repo root or tools/ dir
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from log_aggregator import (
    JSONLogParser,
    TextLogParser,
    NginxLogParser,
    LogAggregator,
)

# ---------------------------------------------------------------------------
# HAND-WRITTEN FIXTURES  (not generated by the parser)
# ---------------------------------------------------------------------------
# Each fixture is a raw log line exactly as it might appear in an archived
# production log file, paired with the fields we expect the parser to
# extract.  The expected values were computed independently (by hand) from
# the human-readable timestamp / level / service in the line, not by running
# the parser and copying its output.
# ---------------------------------------------------------------------------

# --- JSON fixtures ---------------------------------------------------------

# 1. Standard structured JSON log with ISO-8601 timestamp
JSON_FIXTURE_1 = (
    '{"timestamp": "2024-03-15T10:30:00Z", '
    '"level": "ERROR", '
    '"service": "payment-gateway", '
    '"message": "Failed to connect to upstream database", '
    '"request_id": "abc-123-def", '
    '"duration_ms": 4502}'
)

# 2. JSON with alternate field names (severity, logger, msg)
JSON_FIXTURE_2 = (
    '{"time": "2024-03-15T11:45:22Z", '
    '"severity": "WARN", '
    '"logger": "auth-service", '
    '"msg": "Rate limit threshold approaching", '
    '"client_ip": "10.0.0.42"}'
)

# 3. JSON with @timestamp (Elasticsearch common-log-format style)
JSON_FIXTURE_3 = (
    '{"@timestamp": "2024-03-15T08:15:03Z", '
    '"level": "INFO", '
    '"app": "user-service", '
    '"event": "User profile updated successfully", '
    '"user_id": 88412}'
)

# --- Plain text fixtures ---------------------------------------------------

# 4. ISO-8601 timestamp with bracketed service name
TEXT_FIXTURE_1 = (
    "2024-03-15T10:30:00 [order-service] ERROR: "
    "Order #55423 failed validation - invalid shipping address"
)

# 5. Standard (space-separated) timestamp with WARNING level
TEXT_FIXTURE_2 = (
    "2024-03-15 14:22:10 [inventory-service] WARNING: "
    "Stock level below threshold for SKU-9921"
)

# 6. Syslog-style timestamp (no year) with DEBUG level
TEXT_FIXTURE_3 = (
    "Mar 15 09:05:41 [scheduler] DEBUG: "
    "Cron job 'cleanup-temp' executed in 12ms"
)

# --- Nginx access log fixtures ---------------------------------------------

# 7. Nginx 200 OK (info level)
NGINX_FIXTURE_1 = (
    '127.0.0.1 - alice [15/Mar/2024:10:30:00 +0000] '
    '"GET /api/v1/users HTTP/1.1" 200 1024 '
    '"https://app.example.com/dashboard" "Mozilla/5.0"'
)

# 8. Nginx 404 (warn level)
NGINX_FIXTURE_2 = (
    '10.0.0.5 - - [15/Mar/2024:11:45:22 +0000] '
    '"GET /assets/missing.css HTTP/1.1" 404 0 '
    '"-" "Mozilla/5.0 (compatible; BotDetector/2.0)"'
)

# 9. Nginx 502 (error level)
NGINX_FIXTURE_3 = (
    '10.0.0.99 - - [15/Mar/2024:14:00:01 +0000] '
    '"POST /api/v1/checkout HTTP/1.1" 502 0 '
    '"https://app.example.com/cart" "curl/8.4.0"'
)

# --- Malformed / unsupported lines -----------------------------------------

# 10. Completely garbled line (not JSON, not nginx, not a known text format)
MALFORMED_FIXTURE_1 = "###@@@!!! this is not a valid log line @@@###"

# 11. Truncated JSON (missing closing brace)
MALFORMED_FIXTURE_2 = '{"timestamp": "2024-03-15T10:30:00Z", "level": "ERROR"'

# 12. Empty string
MALFORMED_FIXTURE_3 = ""


# ---------------------------------------------------------------------------
# Helper: compute expected epoch timestamps independently
# ---------------------------------------------------------------------------

def _epoch(dt_str: str, fmt: str = "%Y-%m-%dT%H:%M:%S") -> int:
    """Convert a human timestamp to UTC epoch seconds (independent of parser)."""
    dt = datetime.strptime(dt_str, fmt)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return int(dt.timestamp())


# Pre-computed expected timestamps (computed here, NOT from the parser)
EXPECTED_TS_10_30_00 = _epoch("2024-03-15T10:30:00")
EXPECTED_TS_11_45_22 = _epoch("2024-03-15T11:45:22")
EXPECTED_TS_08_15_03 = _epoch("2024-03-15T08:15:03")
EXPECTED_TS_14_22_10 = _epoch("2024-03-15 14:22:10", "%Y-%m-%d %H:%M:%S")


# ---------------------------------------------------------------------------
# Test classes
# ---------------------------------------------------------------------------

class TestJSONLogParser(unittest.TestCase):
    """Focused tests for JSONLogParser — timestamp, level, service, key fields."""

    def setUp(self):
        self.parser = JSONLogParser()

    def test_standard_fields(self):
        """Fixture 1: standard JSON with timestamp/level/service/message."""
        entry = self.parser.parse(JSON_FIXTURE_1)
        self.assertIsNotNone(entry, "Parser should parse valid JSON")
        self.assertEqual(entry["format"], "json")
        # Timestamp — parser normalises ISO-8601 string to epoch seconds
        self.assertEqual(entry["timestamp"], EXPECTED_TS_10_30_00)
        # Level should be preserved as-is from the JSON
        self.assertEqual(entry["level"], "ERROR")
        # Service
        self.assertEqual(entry["service"], "payment-gateway")
        # Message
        self.assertEqual(entry["message"], "Failed to connect to upstream database")
        # Key fields preserved in 'fields'
        self.assertEqual(entry["fields"]["request_id"], "abc-123-def")
        self.assertEqual(entry["fields"]["duration_ms"], 4502)

    def test_alternate_field_names(self):
        """Fixture 2: severity/logger/msg alternate field names."""
        entry = self.parser.parse(JSON_FIXTURE_2)
        self.assertIsNotNone(entry)
        self.assertEqual(entry["format"], "json")
        # Timestamp normalised to epoch
        self.assertEqual(entry["timestamp"], EXPECTED_TS_11_45_22)
        self.assertEqual(entry["level"], "WARN")
        self.assertEqual(entry["service"], "auth-service")
        self.assertEqual(entry["message"], "Rate limit threshold approaching")
        # Key field
        self.assertEqual(entry["fields"]["client_ip"], "10.0.0.42")

    def test_elasticsearch_style(self):
        """Fixture 3: @timestamp / app / event style."""
        entry = self.parser.parse(JSON_FIXTURE_3)
        self.assertIsNotNone(entry)
        self.assertEqual(entry["format"], "json")
        # Timestamp normalised to epoch
        self.assertEqual(entry["timestamp"], EXPECTED_TS_08_15_03)
        self.assertEqual(entry["level"], "INFO")
        self.assertEqual(entry["service"], "user-service")
        self.assertEqual(entry["message"], "User profile updated successfully")
        # Key field
        self.assertEqual(entry["fields"]["user_id"], 88412)

    def test_truncated_json_returns_none(self):
        """Fixture 11: truncated JSON must not crash — should return None."""
        entry = self.parser.parse(MALFORMED_FIXTURE_2)
        self.assertIsNone(entry, "Truncated JSON should return None, not crash")

    def test_non_json_line_returns_none(self):
        """Fixture 10: garbled text is not valid JSON — should return None."""
        entry = self.parser.parse(MALFORMED_FIXTURE_1)
        self.assertIsNone(entry, "Non-JSON line should return None from JSONLogParser")


class TestTextLogParser(unittest.TestCase):
    """Focused tests for TextLogParser — timestamp, level, service, format."""

    def setUp(self):
        self.parser = TextLogParser()

    def test_iso_timestamp_with_service(self):
        """Fixture 4: ISO-8601 ts + [service] + ERROR level."""
        entry = self.parser.parse(TEXT_FIXTURE_1)
        self.assertIsNotNone(entry)
        self.assertEqual(entry["format"], "text")
        # Timestamp — extract_timestamp should find ISO pattern
        self.assertIsNotNone(entry["timestamp"])
        self.assertEqual(entry["timestamp"], EXPECTED_TS_10_30_00)
        # Level
        self.assertEqual(entry["level"], "error")
        # Service — extracted from [order-service] bracket
        self.assertEqual(entry["service"], "order-service")
        # Message is the raw line
        self.assertEqual(entry["message"], TEXT_FIXTURE_1.strip())

    def test_standard_timestamp_warning_level(self):
        """Fixture 5: space-separated ts + WARNING level."""
        entry = self.parser.parse(TEXT_FIXTURE_2)
        self.assertIsNotNone(entry)
        self.assertEqual(entry["format"], "text")
        self.assertEqual(entry["timestamp"], EXPECTED_TS_14_22_10)
        self.assertEqual(entry["level"], "warn")
        self.assertEqual(entry["service"], "inventory-service")

    def test_syslog_timestamp_debug_level(self):
        """Fixture 6: syslog ts (no year) + DEBUG level."""
        entry = self.parser.parse(TEXT_FIXTURE_3)
        self.assertIsNotNone(entry)
        self.assertEqual(entry["format"], "text")
        # Syslog timestamps lack year; parser will use year 1900 (Python default)
        # We verify it is not None and is an int
        self.assertIsNotNone(entry["timestamp"])
        self.assertIsInstance(entry["timestamp"], int)
        self.assertEqual(entry["level"], "debug")
        self.assertEqual(entry["service"], "scheduler")

    def test_empty_line_returns_none(self):
        """Fixture 12: empty string must not crash."""
        entry = self.parser.parse(MALFORMED_FIXTURE_3)
        self.assertIsNone(entry, "Empty line should return None")


class TestNginxLogParser(unittest.TestCase):
    """Focused tests for NginxLogParser — timestamp, level, service, key fields."""

    def setUp(self):
        self.parser = NginxLogParser()

    def test_200_ok_info_level(self):
        """Fixture 7: nginx 200 → info level."""
        entry = self.parser.parse(NGINX_FIXTURE_1)
        self.assertIsNotNone(entry)
        self.assertEqual(entry["format"], "nginx")
        self.assertEqual(entry["level"], "info")
        self.assertEqual(entry["service"], "nginx")
        # Timestamp — nginx pattern includes +0000 offset
        self.assertIsNotNone(entry["timestamp"])
        self.assertEqual(entry["timestamp"], EXPECTED_TS_10_30_00)
        # Key fields
        self.assertEqual(entry["fields"]["remote_addr"], "127.0.0.1")
        self.assertEqual(entry["fields"]["remote_user"], "alice")
        self.assertEqual(entry["fields"]["status"], 200)
        self.assertEqual(entry["fields"]["body_bytes"], "1024")
        self.assertEqual(entry["fields"]["request"], "GET /api/v1/users HTTP/1.1")
        self.assertEqual(entry["fields"]["referer"], "https://app.example.com/dashboard")
        self.assertEqual(entry["fields"]["user_agent"], "Mozilla/5.0")
        # Message should be the request line
        self.assertEqual(entry["message"], "GET /api/v1/users HTTP/1.1")

    def test_404_warn_level(self):
        """Fixture 8: nginx 404 → warn level."""
        entry = self.parser.parse(NGINX_FIXTURE_2)
        self.assertIsNotNone(entry)
        self.assertEqual(entry["level"], "warn")
        self.assertEqual(entry["fields"]["status"], 404)
        self.assertEqual(entry["fields"]["remote_addr"], "10.0.0.5")
        self.assertEqual(entry["fields"]["body_bytes"], "0")

    def test_502_error_level(self):
        """Fixture 9: nginx 502 → error level."""
        entry = self.parser.parse(NGINX_FIXTURE_3)
        self.assertIsNotNone(entry)
        self.assertEqual(entry["level"], "error")
        self.assertEqual(entry["fields"]["status"], 502)
        self.assertEqual(entry["fields"]["request"], "POST /api/v1/checkout HTTP/1.1")
        self.assertEqual(entry["fields"]["user_agent"], "curl/8.4.0")

    def test_non_nginx_line_returns_none(self):
        """Fixture 10: garbled text should not match nginx pattern."""
        entry = self.parser.parse(MALFORMED_FIXTURE_1)
        self.assertIsNone(entry, "Non-nginx line should return None from NginxLogParser")


class TestMalformedAndAggregator(unittest.TestCase):
    """Malformed-line resilience + aggregator integration tests."""

    def test_aggregator_does_not_crash_on_malformed(self):
        """All malformed fixtures must be processed without raising."""
        agg = LogAggregator()
        for line in [MALFORMED_FIXTURE_1, MALFORMED_FIXTURE_2, MALFORMED_FIXTURE_3]:
            # _parse_line returns False for unparsable lines but must not raise
            result = agg._parse_line(line)
            # Garbled text may still match TextLogParser (it parses anything non-empty);
            # the key requirement is: no crash.
            self.assertIsInstance(result, bool)

    def test_aggregator_processes_mixed_formats(self):
        """Aggregator should handle JSON, text, and nginx lines together."""
        agg = LogAggregator()
        all_lines = [
            JSON_FIXTURE_1,
            JSON_FIXTURE_2,
            JSON_FIXTURE_3,
            TEXT_FIXTURE_1,
            TEXT_FIXTURE_2,
            TEXT_FIXTURE_3,
            NGINX_FIXTURE_1,
            NGINX_FIXTURE_2,
            NGINX_FIXTURE_3,
        ]
        for line in all_lines:
            agg._parse_line(line)

        self.assertEqual(len(agg.entries), 9)
        # Check level counts
        self.assertGreater(agg.level_counts["error"], 0)
        self.assertGreater(agg.level_counts["warn"], 0)
        self.assertGreater(agg.level_counts["info"], 0)
        # Check service counts include expected services
        services = set(agg.service_counts.keys())
        self.assertIn("nginx", services)
        self.assertIn("payment-gateway", services)

    def test_malformed_garbled_line_text_parser_does_not_crash(self):
        """The garbled line (fixture 10) will be caught by TextLogParser
        since TextLogParser parses any non-empty line.  Verify it produces
        a valid entry without crashing and has format='text'."""
        parser = TextLogParser()
        entry = parser.parse(MALFORMED_FIXTURE_1)
        # TextLogParser parses any non-empty stripped line, so this will be
        # an entry with unknown level — the point is it must not crash.
        self.assertIsNotNone(entry)
        self.assertEqual(entry["format"], "text")
        self.assertEqual(entry["level"], "unknown")


# ---------------------------------------------------------------------------
# Standalone runner
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    unittest.main(verbosity=2)