#!/usr/bin/env python3
"""
Independent parser fixture tests for log_aggregator.py.

These tests use hand-written log fixture files (NOT generated by the parser)
to verify parser behavior independently.
"""

import os
import sys
import unittest
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from log_aggregator import JSONLogParser, TextLogParser, NginxLogParser, LogAggregator

FIXTURES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "test_fixtures")


def read_fixture(name):
    path = os.path.join(FIXTURES_DIR, name)
    with open(path, 'r', encoding='utf-8') as f:
        return [line.rstrip('\n') for line in f]


class TestJSONParserFixtures(unittest.TestCase):
    """Test JSON log parser against hand-written fixtures."""

    @classmethod
    def setUpClass(cls):
        cls.lines = read_fixture("json_fixtures.log")
        cls.parser = JSONLogParser()
        cls.parsed = [cls.parser.parse(line) for line in cls.lines]

    def test_all_lines_parse(self):
        """All valid JSON fixture lines should parse successfully."""
        parsed_count = sum(1 for p in self.parsed if p is not None)
        self.assertEqual(parsed_count, len(self.lines),
                         f"Only {parsed_count}/{len(self.lines)} lines parsed")

    def test_timestamp_extraction(self):
        """Each parsed entry should have a timestamp."""
        for i, entry in enumerate(self.parsed):
            if entry:
                self.assertIsNotNone(entry.get('timestamp'),
                                     f"Line {i+1}: missing timestamp")

    def test_level_extraction(self):
        """Level should be extracted correctly from each entry."""
        expected_levels = [
            'info', 'debug', 'warn', 'error', 'info',
            'error', 'critical', 'info', 'debug', 'error',
        ]
        for i, (entry, expected) in enumerate(zip(self.parsed, expected_levels)):
            if entry:
                self.assertEqual(entry.get('level', '').lower(), expected,
                                 f"Line {i+1}: expected level '{expected}', got '{entry.get('level')}'")

    def test_service_extraction(self):
        """Service name should be extracted correctly."""
        expected_services = [
            'backend', 'backend', 'backend', 'backend', 'market',
            'backend', 'frailbox', 'frontend', 'backend', 'market',
        ]
        for i, (entry, expected) in enumerate(zip(self.parsed, expected_services)):
            if entry:
                self.assertEqual(entry.get('service', ''), expected,
                                 f"Line {i+1}: expected service '{expected}', got '{entry.get('service')}'")

    def test_format_marker(self):
        """All JSON entries should have format='json'."""
        for i, entry in enumerate(self.parsed):
            if entry:
                self.assertEqual(entry.get('format'), 'json',
                                 f"Line {i+1}: expected format 'json'")


class TestTextParserFixtures(unittest.TestCase):
    """Test text log parser against hand-written fixtures."""

    @classmethod
    def setUpClass(cls):
        cls.lines = read_fixture("text_fixtures.log")
        cls.parser = TextLogParser()
        cls.parsed = [cls.parser.parse(line) for line in cls.lines]

    def test_all_lines_parse(self):
        parsed_count = sum(1 for p in self.parsed if p is not None)
        self.assertEqual(parsed_count, len(self.lines),
                         f"Only {parsed_count}/{len(self.lines)} lines parsed")

    def test_level_extraction(self):
        expected_levels = [
            'info', 'debug', 'warn', 'error', 'info',
            'error', 'error', 'info', 'debug', 'error',
        ]
        for i, (entry, expected) in enumerate(zip(self.parsed, expected_levels)):
            if entry:
                self.assertEqual(entry.get('level', '').lower(), expected,
                                 f"Line {i+1}: expected level '{expected}', got '{entry.get('level')}'")

    def test_service_extraction(self):
        expected_services = [
            'backend', 'backend', 'backend', 'backend', 'market',
            'backend', 'frailbox', 'frontend', 'backend', 'market',
        ]
        for i, (entry, expected) in enumerate(zip(self.parsed, expected_services)):
            if entry:
                self.assertEqual(entry.get('service', ''), expected,
                                 f"Line {i+1}: expected service '{expected}', got '{entry.get('service')}'")

    def test_format_marker(self):
        for i, entry in enumerate(self.parsed):
            if entry:
                self.assertEqual(entry.get('format'), 'text',
                                 f"Line {i+1}: expected format 'text'")


class TestNginxParserFixtures(unittest.TestCase):
    """Test nginx log parser against hand-written fixtures."""

    @classmethod
    def setUpClass(cls):
        cls.lines = read_fixture("nginx_fixtures.log")
        cls.parser = NginxLogParser()
        cls.parsed = [cls.parser.parse(line) for line in cls.lines]

    def test_all_lines_parse(self):
        parsed_count = sum(1 for p in self.parsed if p is not None)
        self.assertEqual(parsed_count, len(self.lines),
                         f"Only {parsed_count}/{len(self.lines)} lines parsed")

    def test_status_based_level(self):
        """Level should reflect HTTP status codes."""
        expected_levels = ['info', 'info', 'info', 'warn', 'info',
                          'error', 'info', 'info', 'error', 'warn']
        for i, (entry, expected) in enumerate(zip(self.parsed, expected_levels)):
            if entry:
                self.assertEqual(entry.get('level', '').lower(), expected,
                                 f"Line {i+1}: expected level '{expected}' for status code")

    def test_service_is_nginx(self):
        for i, entry in enumerate(self.parsed):
            if entry:
                self.assertEqual(entry.get('service'), 'nginx',
                                 f"Line {i+1}: expected service 'nginx'")

    def test_request_method_extraction(self):
        """Fields should contain the HTTP method from the request."""
        entry = self.parsed[0]
        if entry:
            self.assertIn('GET', entry.get('message', ''),
                          "First line should contain GET in request")

    def test_remote_addr_present(self):
        for i, entry in enumerate(self.parsed):
            if entry:
                self.assertIsNotNone(entry.get('fields', {}).get('remote_addr'),
                                     f"Line {i+1}: missing remote_addr")


class TestMalformedFixtures(unittest.TestCase):
    """Test parser resilience against malformed input."""

    @classmethod
    def setUpClass(cls):
        cls.lines = read_fixture("malformed_fixtures.log")
        cls.json_parser = JSONLogParser()
        cls.text_parser = TextLogParser()
        cls.nginx_parser = NginxLogParser()

    def test_no_crash_on_malformed(self):
        """Parsing malformed lines should never raise exceptions."""
        for i, line in enumerate(self.lines):
            for parser_name, parser in [('json', self.json_parser),
                                         ('text', self.text_parser),
                                         ('nginx', self.nginx_parser)]:
                try:
                    parser.parse(line)
                except Exception as e:
                    self.fail(f"Line {i+1} crashed {parser_name} parser: {e}")

    def test_malformed_lines_return_none(self):
        """Completely unstructured lines should return None (not crash)."""
        # Lines 0, 1, 3, 5, 6, 7 are malformed/unstructured
        for idx in [0, 1, 3, 5, 6, 7]:
            line = self.lines[idx] if idx < len(self.lines) else ''
            if not line.strip():
                continue
            result = self.json_parser.parse(line)
            # Should either not crash — None is fine
            self.assertIsNone(result or None)  # json parser returns None for non-json


class TestAggregatorWithFixtures(unittest.TestCase):
    """Test LogAggregator using fixture files end-to-end."""

    def test_aggregator_processes_json_fixtures(self):
        agg = LogAggregator()
        count = agg.process_file(os.path.join(FIXTURES_DIR, "json_fixtures.log"))
        self.assertEqual(count, 10, "Should parse all 10 JSON fixture lines")
        self.assertEqual(agg.level_counts.get('info', 0), 3)
        self.assertEqual(agg.level_counts.get('error', 0), 3)
        self.assertEqual(agg.level_counts.get('debug', 0), 2)
        self.assertEqual(agg.level_counts.get('warn', 0), 1)
        self.assertEqual(agg.level_counts.get('critical', 0), 1)

    def test_aggregator_processes_text_fixtures(self):
        agg = LogAggregator()
        count = agg.process_file(os.path.join(FIXTURES_DIR, "text_fixtures.log"))
        self.assertEqual(count, 10, "Should parse all 10 text fixture lines")

    def test_aggregator_processes_nginx_fixtures(self):
        agg = LogAggregator()
        count = agg.process_file(os.path.join(FIXTURES_DIR, "nginx_fixtures.log"))
        self.assertEqual(count, 10, "Should parse all 10 nginx fixture lines")

    def test_malformed_does_not_crash_aggregator(self):
        """The aggregator should not crash or count malformed lines."""
        agg = LogAggregator()
        count = agg.process_file(os.path.join(FIXTURES_DIR, "malformed_fixtures.log"))
        # Only the valid JSON line (index 4) should parse
        self.assertGreaterEqual(count, 0, "Aggregator should not crash on malformed input")
        # Verify no crash
        summary = agg.get_summary()
        self.assertIn('total_entries', summary)

    def test_mixed_fixtures_directory(self):
        """Process all fixtures at once."""
        agg = LogAggregator()
        total = agg.process_directory(FIXTURES_DIR, "*.log")
        self.assertGreaterEqual(total, 30, "Should parse at least 30 lines across all fixture files")
        summary = agg.get_summary()
        self.assertGreater(summary['total_entries'], 0)
        self.assertIn('by_level', summary)
        self.assertIn('by_service', summary)


if __name__ == "__main__":
    unittest.main()
