#!/usr/bin/env python3
"""
Independent parser fixture validation for log_aggregator parsers.

This script tests JSONLogParser, TextLogParser, and NginxLogParser against
hand-written representative log lines — NOT parser-generated samples.

The legacy test suite had a ~40% false-pass rate because test data was
generated by the same parsers it was supposed to validate. These fixtures
are written by hand to exercise exact parser behaviour independently.

Usage:
    python3 tools/test_parsers.py
    python3 tools/test_parsers.py --verbose
"""

import sys
import os
from typing import Any, Dict, List, Optional, Tuple

# Allow running from repo root
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from tools.log_aggregator import JSONLogParser, TextLogParser, NginxLogParser

# ---------------------------------------------------------------------------
# INDEPENDENT FIXTURES (hand-written, NOT parser-generated)
# ---------------------------------------------------------------------------

JSON_FIXTURES: List[Tuple[str, Optional[Dict[str, Any]], str]] = [
    # (input line, expected fields or None=should parse, description)
    (
        '{"timestamp":"2024-03-15T08:30:00Z","level":"error","service":"auth","message":"Invalid token for user 42"}',
        {"level": "error", "service": "auth", "format": "json"},
        "standard JSON log entry with timestamp, level, service, message",
    ),
    (
        '{"time":"2024-03-15T09:00:00Z","severity":"warn","logger":"payment","msg":"Retry attempt 3/5"}',
        {"level": "warn", "service": "payment", "format": "json"},
        "JSON with 'time'/'severity'/'logger'/'msg' field aliases",
    ),
    (
        '{"@timestamp":"2024-03-15T10:00:00Z","lvl":"info","app":"gateway","event":"Connection established"}',
        {"level": "info", "service": "gateway", "format": "json"},
        "JSON with '@timestamp'/'lvl'/'app'/'event' field aliases",
    ),
    (
        '{"service":"worker","message":"Job completed"}',
        {"level": "info", "service": "worker", "format": "json"},
        "JSON with minimal fields — level defaults to 'info'",
    ),
    (
        '{"timestamp":"2024-06-01T12:00:00Z","level":"debug","message":"Cache hit for key user:123"}',
        {"level": "debug", "service": None, "format": "json"},
        "JSON with no service field — should be None",
    ),
    # Malformed / edge cases — should not crash
    (
        "",
        None,
        "empty string — parser should return None gracefully",
    ),
    (
        "not json at all",
        None,
        "non-JSON text — parser should return None gracefully",
    ),
    (
        "[1, 2, 3]",
        None,
        "JSON array instead of object — parser should return None",
    ),
    (
        '{"level":"info"',
        None,
        "truncated/invalid JSON — parser should return None gracefully",
    ),
]

TEXT_FIXTURES: List[Tuple[str, Optional[Dict[str, Any]], str]] = [
    (
        "2024-03-15 08:30:00 [auth] ERROR: Invalid credentials for user admin",
        {"level": "error", "service": "auth", "format": "text"},
        "standard text log: timestamp, service bracket, ERROR level, message",
    ),
    (
        "2024-03-15T09:00:00 WARNING: Connection pool nearly exhausted (95/100)",
        {"level": "warn", "service": None, "format": "text"},
        "ISO timestamp, WARNING level, no service tag",
    ),
    (
        "2024-03-15 10:30:00 INFO: Scheduled job 'cleanup' completed in 2.4s",
        {"level": "info", "service": None, "format": "text"},
        "standard timestamp, INFO level",
    ),
    (
        "[backup] Mar 15 14:30:00 DEBUG: Starting incremental backup phase 1/3",
        {"level": "debug", "service": "backup", "format": "text"},
        "syslog-style timestamp, service bracket at start, DEBUG level",
    ),
    (
        "ERROR [database]: Connection refused after 3 retries",
        {"level": "error", "service": "database", "format": "text"},
        "ERROR at start, service in brackets",
    ),
    (
        "FATAL: Out of memory in allocator region 'heap-main'",
        {"level": "error", "service": None, "format": "text"},
        "FATAL level — should map to 'error'",
    ),
    (
        "CRITICAL [core]: Kernel panic - not syncing: Attempted to kill init!",
        {"level": "error", "service": "core", "format": "text"},
        "CRITICAL level — should map to 'error'",
    ),
    (
        "2024-06-01 12:00:00 [api] NOTICE: Deprecated endpoint /v1/users called",
        {"level": "info", "service": "api", "format": "text"},
        "NOTICE level — should map to 'info'",
    ),
    (
        "2024-06-01 12:00:00 [worker] TRACE: Entering function handle_request()",
        {"level": "debug", "service": "worker", "format": "text"},
        "TRACE level — should map to 'debug'",
    ),
    # Malformed / edge cases
    (
        "",
        None,
        "empty string — parser should return None gracefully",
    ),
    (
        "Just a plain message without any structure",
        {"level": "unknown", "service": None, "format": "text"},
        "plain text — should parse with 'unknown' level (no crash)",
    ),
    (
        "   \t  ",
        None,
        "whitespace-only — parser should return None gracefully",
    ),
]

NGINX_FIXTURES: List[Tuple[str, Optional[Dict[str, Any]], str]] = [
    (
        '192.168.1.10 - admin [15/Mar/2024:08:30:00 +0000] "GET /api/users HTTP/1.1" 200 1234 "-" "Mozilla/5.0"',
        {"level": "info", "service": "nginx", "format": "nginx"},
        "standard nginx access log — 200 OK → info level",
    ),
    (
        '10.0.0.5 - - [15/Mar/2024:08:31:00 +0000] "POST /api/login HTTP/1.1" 401 45 "-" "curl/7.88.1"',
        {"level": "warn", "service": "nginx", "format": "nginx"},
        "nginx 401 — should map to 'warn' level",
    ),
    (
        '172.16.0.3 - - [15/Mar/2024:08:32:00 +0000] "GET /admin HTTP/1.1" 403 153 "-" "python-requests/2.31.0"',
        {"level": "warn", "service": "nginx", "format": "nginx"},
        "nginx 403 — should map to 'warn' level",
    ),
    (
        '203.0.113.42 - - [15/Mar/2024:08:33:00 +0000] "GET /api/internal/config HTTP/1.1" 500 83 "-" "Go-http-client/2.0"',
        {"level": "error", "service": "nginx", "format": "nginx"},
        "nginx 500 — should map to 'error' level",
    ),
    (
        '198.51.100.7 - - [15/Mar/2024:08:34:00 +0000] "GET /health HTTP/1.1" 502 173 "-" "ELB-HealthChecker/2.0"',
        {"level": "error", "service": "nginx", "format": "nginx"},
        "nginx 502 — should map to 'error' level",
    ),
    (
        '192.168.1.10 - jsmith [15/Mar/2024:08:35:00 +0000] "DELETE /api/sessions/xyz HTTP/1.1" 204 0 "https://app.example.com/" "Mozilla/5.0"',
        {"level": "info", "service": "nginx", "format": "nginx"},
        "nginx 204 with authenticated user and referer",
    ),
    # Malformed / edge cases
    (
        "",
        None,
        "empty string — parser should return None gracefully",
    ),
    (
        "This is not an nginx log line",
        None,
        "non-nginx text — parser should return None gracefully",
    ),
    (
        'incomplete nginx line without enough fields',
        None,
        "malformed nginx line — parser should return None gracefully",
    ),
]


# ---------------------------------------------------------------------------
# TEST RUNNER
# ---------------------------------------------------------------------------

def run_tests(
    parser_name: str,
    parser,
    fixtures: List[Tuple[str, Optional[Dict[str, Any]], str]],
    verbose: bool = False,
) -> Tuple[int, int, List[str]]:
    """Run fixtures against a parser. Returns (passed, total, failures_descriptions)."""
    passed = 0
    failures: List[str] = []

    for i, (line, expected, description) in enumerate(fixtures):
        try:
            result = parser.parse(line)
        except Exception as e:
            # Should not crash on any input
            failures.append(
                f"  [{parser_name}] fixture {i}: CRASH on '{line[:60]}' — {type(e).__name__}: {e}"
            )
            if verbose:
                print(f"  FAIL [{parser_name}] #{i}: CRASH — {description}")
            continue

        if expected is None:
            # Expected to return None (malformed/unparseable)
            if result is None:
                passed += 1
                if verbose:
                    print(f"  OK   [{parser_name}] #{i}: correctly returns None — {description}")
            else:
                failures.append(
                    f"  [{parser_name}] fixture {i}: expected None, got {result}"
                )
                if verbose:
                    print(f"  FAIL [{parser_name}] #{i}: expected None — {description}")
        else:
            if result is None:
                failures.append(
                    f"  [{parser_name}] fixture {i}: expected dict, got None — {description}"
                )
                if verbose:
                    print(f"  FAIL [{parser_name}] #{i}: expected dict, got None — {description}")
                continue

            # Check required fields
            for field, expected_val in expected.items():
                actual_val = result.get(field)
                if actual_val != expected_val:
                    failures.append(
                        f"  [{parser_name}] fixture {i}: field '{field}' expected '{expected_val}', got '{actual_val}' — {description}"
                    )
                    if verbose:
                        print(f"  FAIL [{parser_name}] #{i}: {field} mismatch ({expected_val} vs {actual_val}) — {description}")
                else:
                    if verbose and field == "level":
                        pass  # Will print OK below

            if not any(f"[{parser_name}] fixture {i}:" in f for f in failures[-len(expected):]):
                passed += 1
                if verbose:
                    print(f"  OK   [{parser_name}] #{i}: {description}")

    return passed, len(fixtures), failures


def main():
    verbose = "--verbose" in sys.argv or "-v" in sys.argv

    print("=" * 60)
    print("  Independent Parser Fixture Validation")
    print("  (hand-written fixtures, NOT parser-generated)")
    print("=" * 60)

    parsers = [
        ("JSONLogParser", JSONLogParser(), JSON_FIXTURES),
        ("TextLogParser", TextLogParser(), TEXT_FIXTURES),
        ("NginxLogParser", NginxLogParser(), NGINX_FIXTURES),
    ]

    total_passed = 0
    total_tests = 0
    all_failures: List[str] = []

    for name, parser, fixtures in parsers:
        print(f"\n--- {name} ({len(fixtures)} fixtures) ---")
        passed, total, failures = run_tests(name, parser, fixtures, verbose=verbose)
        total_passed += passed
        total_tests += total
        all_failures.extend(failures)
        print(f"  Result: {passed}/{total} passed")

    print("\n" + "=" * 60)
    print(f"  TOTAL: {total_passed}/{total_tests} passed")

    if all_failures:
        print(f"\n  FAILURES ({len(all_failures)}):")
        for f in all_failures:
            print(f)
        print()
        return 1
    else:
        print("  ✓ All fixtures passed\n")
        return 0


if __name__ == "__main__":
    sys.exit(main())
